### ISSUE TITLE
Špatně se zobrazující stránka aktualit

### ISSUE THREAD

**Issue by PeKne** [kudlav/css-wis#1]
V kartě aktualit se špatně zobrazují jednotlivé texty. Jsou roztažené až k pravému boku obrazovky a přetékají hlavní tělo vzhledu.

Jinak dobrá práce, dík za sdílení.

**Comment by kudlav** [comment]
Problém si mi podařilo reprodukovat. 
~~Mělo by to být opraveno v https://github.com/kudlav/css-wis/commit/8448e41e01dc7843eabc4dbf57f5c274064792c8~~

**Comment by kudlav** [comment]
Opraveno v https://github.com/kudlav/css-wis/commit/150f005c6d862d6912720a8f22d9434656bce12e (v1.3)
Otestuj a dej vědět.

**Comment by PeKne** [comment]
funguje, super.
